### ISSUE TITLE
[AVM Module Issue]: startup_probe variable naming

### ISSUE THREAD

**Issue by alefteris** [Azure/terraform-azurerm-avm-res-app-containerapp#53]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.1.0

### Description

The `startup_probe` variable name is using singular instead of plural form, when it accepts a list of objects. The other two probe types, `readiness_probes` and `liveness_probes` are using the plural form.

I'm not too familiar with how the probs work, so I could be missing something, but just wanted to ask in case there is a mistake with the naming.

**Comment by lonegunmanb** [comment]
Thanks @alefteris for opening this issue to us. The name is derived from [`startup_probe` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_app#startup_probe-10) and the variable block is generated by [`newres`](https://github.com/lonegunmanb/newres).

In Terraform, we have two different data types in a resource block: attributes and nested blocks. A nested block field must be a collection type, it could be a list, or a set. Most of times we'll set a maximum length to `1`, in that case, it represents an object actually. But if we don't have a maximum length, or the length is greater than `1`, as Terraform config author you can declare this nested block for multiple times. Let's say, for this `startup_probe` block, it is a list of object, but in resource schema we cannot use `startup_probes`, because if that's the case each nested block inside the container app resource must be declared as `startup_probes`, which looks weird.

Then I use `newres` to generate the resource block along with the variable block from the resource schema, it just used the name from the schema. If we'd like to add `s` here it would make things really complicated.

I hope it could answer your question and I'm closing this issue since we're not going to fix it. But please feel free to reopen it if you have different thought.
