### ISSUE TITLE
[AVM Module Issue]: Support argument to ignore changes related to the deployed container version

### ISSUE THREAD

**Issue by alefteris** [Azure/terraform-azurerm-avm-res-app-containerapp#54]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.0

### Description

Currently this module can be used only when deploying new container versions is done only through Terraform. I think this is not the common way many people will deploy their application. Many people, myself included, will deploy new container versions for the application through a separate pipeline using for example the az cli or the Azure Pipeline AzureContainerApps@1 task in order to update just the container.

In this scenario, Terraform state drift will be caused because the following things are getting tracked for changes by Terraform and also will be changed externally from the pipeline after every deployment:

- template.0.container[0].image

Would it be possible to add an extra argument in the module to set whether the revision scope will be managed by the module or not?

I think to implement this with the current Terraform version, a clone of the azurerm_container_app resource will need to be added, with the necessary lifecycle ignore_changes. This clone resource would be created instead of the normal one when the new "manage_revisions" argument is set to false.

**Comment by bonddim** [comment]
In my mind, this module can be buried after this issue was closed unresolved.

Agreed with recommendations from Hashicorp to manage all changes through Terraform. 
But those are only recommendations, and in some cases (like this one) an exception can be made.

Instead of using simle single cli call or task as was described, users are forced to make simple things over-complicated by triggering tf pipeline (which will include other resources for 100%) or storing tf code with app code or anything else.
