### ISSUE TITLE
[AVM Module Issue]: should lists in var.template be maps to prevent re-ordering issues?

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-app-containerapp#60]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

Example - inside the template variable there is a `containers` list of objects - I think this should be a map to prevent problems when re-ordering items.

**Comment by lonegunmanb** [comment]
Thanks @kewalaka for opening this issue to us, after checking the [provider schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containerapps/helpers/container_apps.go#L1002-L1007) I don't think a map could work, since the resource schema defines containers as list of objects. WDYT?

**Comment by kewalaka** [comment]
the items could still be passed to the provider as a list - but by having it as a map in the module I hoped that would avoid issues where (for example) adding a container to the template causes a re-ordering of the list elements and an unnecessary destroy & re-create.

i haven't tested this though, and I don't really understand the relationship between tf and the underlying provider, so I may be talking nonsense :)

**Comment by lonegunmanb** [comment]
Hi @kewalaka I don't think this could work, since resource schema uses list so order does matter, with a list type in variable at least users could control the order. If we expose the variable type as map, that means the final list order is controlled by a sorting algorithm defined in this module, the users can do nothing if they're not satisfied with it.

If you have any better suggestion you're welcomed to provide us a poc, we'll give it a review and maybe adopt your design, thanks in advance!

**Comment by lonegunmanb** [comment]
@kewalaka I'm closing this issue but please feel free to reopen it if you have any further questions.
